version: '3.9'

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "${PORT:-8080}:8080"
    depends_on:
      - redis
    environment:
      PORT: ${PORT}
      APP_URL: ${APP_URL}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
    command: ["yarn", "start"]

  redis:
    image: "redis/redis-stack:latest"
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: [
      "redis-server",
      "--requirepass", "${REDIS_PASSWORD}",
      "--loadmodule", "/usr/lib/redis/modules/redisearch.so"
    ]
    volumes:
      - redis-data:/data

volumes:
  redis-data:
