services:
  - type: web
    name: FULLSTACK-Habib-Sellami
    plan: free
    buildCommand: yarn --frozen-lockfile install; yarn build
    startCommand: yarn start
    runtime: node
    envVars:
      - key: PORT
        sync: false

      - key: APP_URL
        sync: true

      - key: REDIS_HOST
        sync: false

      - key: REDIS_PORT
        value: 6379

      - key: REDIS_PASSWORD
        sync: false

      - key: JWT_SECRET
        value: 123456
