services:
  - type: web
    name: FULLSTACK-Habib-Sellami
    plan: free
    runtime: node
    envVars:
      - key: PORT
        sync: false
      - key: APP_URL
        sync: true
      - key: REDIS_HOST
        sync: true
      - key: REDIS_PORT
        sync: true
      - key: REDIS_PASSWORD
        sync: true
      - key: JWT_SECRET
        sync: true
